### ISSUE TITLE
Into crash when Starting 'build'...

### ISSUE THREAD

**Issue by yyjFish** [dyuliu/deeptracker#1]
when I run 'gulp' command in the 'deeptracker-master' folder，the program crash...
`
...
[14:43:39] Finished 'tslint' after 3.52 s
[14:43:39] Starting 'lint'...
[14:43:39] Finished 'lint' after 29 μs
[14:43:39] Starting 'build'...
src/client/core/controllers/dashboard.client.controller.ts(247,22): error TS2339: Property 'iter' does not exist on type 'string'.
src/client/core/controllers/dashboard.client.controller.ts(247,42): error TS2339: Property 'iter' does not exist on type 'string'.
src/client/utils/services/data-manager.client.service.ts(13,76): error TS2304: Cannot find name 'IKernelDataType'.
src/client/utils/services/data-manager.client.service.ts(54,7): error TS2322: Type 'IPromise<{}>' is not assignable to type 'IPromise<ILayerDataType>'.
  Type '{}' is not assignable to type 'ILayerDataType'.
    Property 'length' is missing in type '{}'.
src/client/utils/services/data-manager.client.service.ts(57,80): error TS2304: Cannot find name 'IKernelDataType'.
...
`

**Comment by dyuliu** [comment]
I suggest you first check the version of nodejs and typescript, ensuring they are consistent with the ones declared in "package.json".
